version: '3'

services:
  backend:
    build: ./backend
    container_name: hyla-backend
    restart: always
    ports:
      - '5000:5000'
    networks:
      - hyla-network

  frontend:
    build: ./Hylapps
    container_name: hyla-frontend
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - backend
    networks:
      - hyla-network

  mongodb:
    image: mongo
    container_name: hyla-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - hyla-data:/data/db
    ports:
      - '27017:27017'
    networks:
      - hyla-network

networks:
  hyla-network:
    driver: bridge

volumes:
  hyla-data:

